server:
  port: 8090

spring:
  mvc:
    dispatch-options-request: true
  application:
    name: tfg

  datasource:
    url: jdbc:mariadb://localhost:3306/TFG
    password: tfg
    username: USER_TFG
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

    show-sql: true
